version: 1.0.{build}

clone_folder: C:\projects\PolyEngineExamples

image:
- Visual Studio 2017

configuration:
- Release
- Debug

platform:
- x64

environment:
  arch: Win64
  QTDIR: C:\Qt\5.10.1\msvc2017_64
  PATH: '%PATH%;%QTDIR%\bin;'
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: "3.6.0"
  PYTHON_ARCH: "64"
  matrix:
  - PROJECT_PATH: C:\projects\PolyEngineExamples\GlobalGameJam2018Game
    SOLUTION_PATH: C:\projects\PolyEngineExamples\GlobalGameJam2018Game\Build\PolyJamGame.sln
  - PROJECT_PATH: C:\projects\PolyEngineExamples\SGJ2017Game
    SOLUTION_PATH: C:\projects\PolyEngineExamples\SGJ2017Game\Build\SGJ2017Game.sln
  - PROJECT_PATH: C:\projects\PolyEngineExamples\SandboxPhysics3D
    SOLUTION_PATH: C:\projects\PolyEngineExamples\SandboxPhysics3D\Build\SandboxPhysics3D.sln
  - PROJECT_PATH: C:\projects\PolyEngineExamples\SandboxRendering
    SOLUTION_PATH: C:\projects\PolyEngineExamples\SandboxRendering\Build\SandboxRendering.sln

  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# install python interpreter
install:
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %QTDIR%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- echo %generator%

before_build:
- cmd: |-
    cd C:\projects
    git clone https://github.com/KNTGPolygon/PolyEngine.git
    cd C:\projects\PolyEngine\PolyEngine\Scripts
    python ProjectTool.py -u %PROJECT_PATH%
    

build:
  project: $(SOLUTION_PATH)
  verbosity: minimal
  parallel: true

  
notifications:
- provider: Slack
  auth_token:
    secure: DWi4NgrRL7/v8v7PyZ03XRepd1bk7t482/T7SpHCaELiOt8hWu/pZpgjfUDfXsZA
  channel: ci-build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
  
