sudo: required
dist: trusty

notifications:
  email: false
  slack: polyengine:Fah16tvbyOphIl7FGHAVVhaB

# Enable C++ support
language: cpp

# Enable compiler cache to speed up compilation
cache: ccache

compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
env: 
  global:
    - COMPILER=g++-6
  matrix:
    - GAME_NAME=GlobalGameJam2018Game
    - GAME_NAME=SGJ2017Game
    - GAME_NAME=SandboxPhysics3D
    - GAME_NAME=SandboxRendering

before_install:
  - export CXX=${COMPILER}
  # Add Qt 5.9.2 ppa
  - sudo add-apt-repository --yes ppa:beineri/opt-qt592-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -qq mesa-common-dev libx11-dev git
  - sudo apt-get install -qq libepoxy-dev libsoil-dev libassimp-dev libfreetype6-dev libopenal-dev libogg-dev libvorbis-dev libbox2d-dev libbullet-dev
  - sudo apt-get -y install qt59base
  # Workaround for not working `sudo apt-get install -qq libsdl2-dev` https://github.com/travis-ci/travis-ci/issues/8317
  - wget https://www.libsdl.org/release/SDL2-2.0.7.tar.gz -O SDL2-2.0.7.tar.gz
  - tar -xzf SDL2-2.0.7.tar.gz
  - 

install:
  - (cd SDL2-2.0.7 && ./configure && make && sudo make install)
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version


before_script:
  ############################################################################
  # Go back to the root of the project and setup the build directory
  ############################################################################
  - cd ${TRAVIS_BUILD_DIR}

script:
  - source /opt/qt59/bin/qt59-env.sh
  - git clone https://github.com/KNTGPolygon/PolyEngine.git
  - cd PolyEngine/PolyEngine/Scripts
  - python3 ProjectTool.py -u ${TRAVIS_BUILD_DIR}/${GAME_NAME}
  - cd ${TRAVIS_BUILD_DIR}/${GAME_NAME}/Build
  - make
